packages:
  - apps/*
  - packages/*

allowBuilds:
  '@nestjs/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@nestjs/common@12.1.1'
  - '@nestjs/core@12.1.1'
  - '@nestjs/platform-express@12.1.1'
  - '@typescript-eslint/eslint-plugin@8.71.0'
  - '@typescript-eslint/parser@8.71.0'
  - '@typescript-eslint/project-service@8.71.0'
  - '@typescript-eslint/scope-manager@8.71.0'
  - '@typescript-eslint/tsconfig-utils@8.71.0'
  - '@typescript-eslint/type-utils@8.71.0'
  - '@typescript-eslint/types@8.71.0'
  - '@typescript-eslint/typescript-estree@8.71.0'
  - '@typescript-eslint/utils@8.71.0'
  - '@typescript-eslint/visitor-keys@8.71.0'
  - typescript-eslint@8.71.0
