import {test,expect} from '@playwright/test';
test('real gateway quote and pending booking survive locale/theme switches; owned terminal detail survives refresh',async({page})=>{
  const email=`browser-${Date.now()}@test.invalid`;
  await page.goto('/en/sign-up');
  await page.getByLabel('Your name',{exact:true}).fill('Browser passenger');
  await page.getByLabel('Email address',{exact:true}).fill(email);
  await page.getByLabel('Password',{exact:true}).fill('Browser-registration-2026');
  await page.getByLabel('Confirm password',{exact:true}).fill('Browser-registration-2026');
  await page.getByRole('button',{name:'Create an account',exact:true}).click();
  await expect(page).toHaveURL('/en/account');
  await page.goto('/en/passenger/book');
  await page.getByLabel('Destination',{exact:true}).selectOption('gulshan-1');
  await page.getByLabel('Passenger seats',{exact:true}).selectOption('2');
  await page.getByRole('button',{name:'Calculate fare',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Your fare quote'})).toBeVisible();
  await page.getByRole('button',{name:'Change language to Bangla',exact:true}).click();
  await expect(page).toHaveURL('/bn/passenger/book');
  await expect(page.getByLabel('গন্তব্য',{exact:true})).toHaveValue('gulshan-1');
  await expect(page.getByLabel('যাত্রীর আসনসংখ্যা',{exact:true})).toHaveValue('2');
  await expect(page.getByRole('heading',{name:'আপনার ভাড়ার হিসাব'})).toBeVisible();
  let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});let requests=0;
  await page.route('**/api/v1/ride-requests',async route=>{if(route.request().method()!=='POST')return route.continue();requests++;const response=await route.fetch();await gate;await route.fulfill({response});});
  await page.getByRole('button',{name:'যাত্রার অনুরোধ নিশ্চিত করুন',exact:true}).click();
  await expect.poll(()=>requests).toBe(1);
  await page.getByRole('button',{name:'ইংরেজি ভাষায় পরিবর্তন করুন',exact:true}).click();
  await page.getByRole('button',{name:'Switch to light mode',exact:true}).click();
  const working=page.getByRole('button',{name:'Working…',exact:true});
  await expect(working).toHaveCount(3);
  for(const button of await working.all())await expect(button).toBeDisabled();
  release();
  await expect(page).toHaveURL(/\/en\/passenger\/rides\/[0-9a-f-]+$/);
  expect(requests).toBe(1);
  const stable=page.url();
  await expect(page.getByText('Waiting for acceptance',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Cancel ride',exact:true}).click();
  await page.getByLabel('Cancellation reason',{exact:true}).fill('Browser cancellation');
  await page.getByRole('button',{name:'Confirm cancellation',exact:true}).click();
  await expect(page.getByText('Cancelled',{exact:true})).toBeVisible();
  await page.reload();await expect(page).toHaveURL(stable);await expect(page.getByText('Cancelled',{exact:true})).toBeVisible();
  expect((await page.request.get('/api/v1/ride-requests/current')).status()).toBe(200);
  expect((await (await page.request.get('/api/v1/ride-requests/current')).json()).data).toBeNull();
});
