import {test,expect} from '@playwright/test';import type {Page} from '@playwright/test';import en from '../../apps/web/src/i18n/messages/en.json';import bn from '../../apps/web/src/i18n/messages/bn.json';
async function login(page:Page,actor:string){await page.goto('/en/sign-in');await page.getByLabel(en.email,{exact:true}).fill(actor+'@demo.dhaka.test');await page.getByLabel(en.password,{exact:true}).fill(process.env.E2E_PASSWORD!);await page.getByRole('button',{name:en.signIn,exact:true}).click();await expect(page).toHaveURL('/en/account');}
async function post(page:Page,path:string,body:object,method='POST'){const token=(await (await page.request.get('/api/v1/auth/csrf')).json()).data.csrfToken;const response=await page.request.fetch('/api/v1'+path,{method,data:body,headers:{origin:'http://127.0.0.1:3000','x-csrf-token':token,'idempotency-key':crypto.randomUUID()}});expect(response.ok()).toBe(true);return (await response.json()).data;}
test('arrival then driver cancellation preserves final evidence, displays zero charge in detail/history and excludes graphs; reason survives presentation switches',async({browser,baseURL})=>{
  test.setTimeout(60000);const contexts=await Promise.all([browser.newContext({baseURL}),browser.newContext({baseURL})]);const [n,j]=await Promise.all(contexts.map(x=>x.newPage()));
  try{await login(n,'nusrat');await login(j,'jashim');const quote=await post(n,'/fare-quotes',{pickupId:'banani',destinationId:'mohakhali',seats:1}),ride=(await post(n,'/ride-requests',{quoteId:quote.id,paymentMethod:'CASH'})).resourceId;await post(j,'/driver/availability',{online:true},'PATCH');const pool=(await post(j,`/driver/requests/${ride}/accept`,{})).resourceId;await n.goto('/en/passenger/rides/'+ride);await j.goto('/en/driver/pools/'+pool);await j.getByRole('button',{name:en.driverArrive,exact:true}).click();await j.getByRole('dialog').getByRole('button',{name:en.confirmAction,exact:true}).click();await expect(j.getByRole('dialog')).not.toBeVisible();
    await j.getByRole('button',{name:en.cancelPool,exact:true}).click();const dialog=j.getByRole('dialog');await dialog.getByLabel(en.reason,{exact:true}).fill('Driver emergency — চালকের জরুরি কারণ');await dialog.getByRole('button',{name:en.switchLanguage,exact:true}).click();await expect(j).toHaveURL('/bn/driver/pools/'+pool);await expect(dialog.getByLabel(bn.reason,{exact:true})).toHaveValue('Driver emergency — চালকের জরুরি কারণ');await dialog.getByRole('button',{name:bn.switchLight,exact:true}).click();await dialog.getByRole('button',{name:bn.confirmCancel,exact:true}).click();await expect(dialog).not.toBeVisible();await expect(n.getByText(en.statusCANCELLED,{exact:true})).toBeVisible();await expect(n.getByRole('definition').filter({hasText:'0.00'}).first()).toBeVisible();await expect(n.getByText(en.previousFinal,{exact:false})).toBeVisible();
    const detail=(await (await n.request.get('/api/v1/ride-requests/'+ride)).json()).data;expect(detail.fare.chargePoysha).toBe(0);expect(detail.fare.historicalFinal.totalPoysha).toBe(4000);expect(detail.fare.collectionStatus).toBe('NOT_TRACKED');await n.reload();await expect(n.getByText(en.statusCANCELLED,{exact:true})).toBeVisible();await n.goto('/en/passenger/history');const item=n.getByRole('article').filter({has:n.getByRole('link',{name:en.openDetails,exact:true})}).filter({hasText:'Mohakhali'});await expect(item.first()).toContainText('0.00');const stats=(await (await n.request.get('/api/v1/statistics/passenger')).json()).data;expect(stats.totals.trips).toBe(0);expect(stats.totals.farePoysha).toBe(0);expect((await (await n.request.get('/api/v1/ride-requests/current')).json()).data).toBeNull();
  }finally{await Promise.all(contexts.map(x=>x.close()));}
});
