import {test,expect} from '@playwright/test';import type {Page} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';import en from '../../apps/web/src/i18n/messages/en.json';import bn from '../../apps/web/src/i18n/messages/bn.json';
const copy={en:{email:'Email address',password:'Password',signin:'Sign in',quantity:'Passenger seats',destination:'Destination',quote:'Calculate fare',heading:'Your fare quote',request:'Confirm ride request',online:'Go online',offline:'Go offline',accept:'Accept request',arrive:'Mark arrival',start:'Start trip',complete:'Complete trip',confirm:'Confirm action',completed:'Completed'},bn:{email:'ইমেইল ঠিকানা',password:'পাসওয়ার্ড',signin:'সাইন ইন',quantity:'যাত্রীর আসনসংখ্যা',destination:'গন্তব্য',quote:'ভাড়া হিসাব করুন',heading:'আপনার ভাড়ার হিসাব',request:'যাত্রার অনুরোধ নিশ্চিত করুন',online:'অনলাইনে আসুন',offline:'অফলাইনে যান',accept:'অনুরোধ গ্রহণ করুন',arrive:'পৌঁছানো নিশ্চিত করুন',start:'যাত্রা শুরু করুন',complete:'যাত্রা শেষ করুন',confirm:'কাজ নিশ্চিত করুন',completed:'সম্পন্ন'}};
async function login(page:Page,name:string,locale:'en'|'bn'){const t=copy[locale];await page.goto(`/${locale}/sign-in`);await page.getByLabel(t.email,{exact:true}).fill(name+'@demo.dhaka.test');await page.getByLabel(t.password,{exact:true}).fill(process.env.E2E_PASSWORD!);await page.getByRole('button',{name:t.signin,exact:true}).click();await expect(page).toHaveURL(`/${locale}/account`);}
async function booking(page:Page,locale:'en'|'bn',seats:number,destination:string){const t=copy[locale];await page.goto(`/${locale}/passenger/book`);await page.getByLabel(t.quantity,{exact:true}).selectOption(String(seats));await page.getByLabel(t.destination,{exact:true}).selectOption(destination);await page.getByRole('button',{name:t.quote,exact:true}).click();await expect(page.getByRole('heading',{name:t.heading})).toBeVisible();await page.getByRole('button',{name:t.request,exact:true}).click();await expect(page).toHaveURL(/\/passenger\/rides\/[0-9a-f-]+$/);return page.url().split('/').pop()!;}
for(const [locale,theme] of [['en','dark'],['en','light'],['bn','dark'],['bn','light']] as const)test(`named pooled full journey ${locale}/${theme}, final fares and stable completed refresh`,async({browser,baseURL},info)=>{
  test.setTimeout(60000);const contexts=await Promise.all([browser.newContext({baseURL}),browser.newContext({baseURL}),browser.newContext({baseURL})]);await Promise.all(contexts.map(c=>c.addCookies([{name:'dtp-theme',value:theme,url:baseURL!}])));const [n,r,j]=await Promise.all(contexts.map(c=>c.newPage()));const t=copy[locale];const dictionary=locale==='bn'?bn:en;
  try{
    await login(n,'nusrat',locale);await login(r,'rafiq',locale);await login(j,'jashim',locale);
    const nId=await booking(n,locale,1,'mohakhali'),rId=await booking(r,locale,2,'gulshan-1');
    await j.goto(`/${locale}/driver/requests`);await expect(j.getByRole('button',{name:new RegExp('^('+t.online+'|'+t.offline+')$')})).toBeVisible();if(await j.getByRole('button',{name:t.online,exact:true}).isVisible())await j.getByRole('button',{name:t.online,exact:true}).click();
    await j.getByRole('article').filter({has:j.getByRole('heading',{name:'Nusrat',exact:true})}).getByRole('button',{name:t.accept,exact:true}).click();await expect(j).toHaveURL(/\/driver\/pools\/[0-9a-f-]+$/);const pool=j.url().split('/').pop()!;
    await j.goto(`/${locale}/driver/requests`);await j.getByRole('article').filter({has:j.getByRole('heading',{name:'Rafiq',exact:true})}).getByRole('button',{name:t.accept,exact:true}).click();await expect(j).toHaveURL(`/${locale}/driver/pools/${pool}`);
    await expect.poll(async()=>((await (await n.request.get('/api/v1/ride-requests/'+nId)).json()).data.fare.totalPoysha)).toBe(3000);
    expect((await (await r.request.get('/api/v1/ride-requests/'+rId)).json()).data.fare.totalPoysha).toBe(8000);
    await expect(j.getByText(`${dictionary.poolOccupancy}: ${locale==='bn'?'৩/৩':'3/3'}`,{exact:true})).toBeVisible();
    await info.attach('actual-active-pool-'+locale+'-'+theme,{body:await j.screenshot({fullPage:true}),contentType:'image/png'});
    for(const name of [t.arrive,t.start,t.complete]){const trigger=j.getByRole('button',{name,exact:true});await trigger.click();if(name===t.arrive){const dialog=j.getByRole('dialog');await dialog.getByRole('button',{name:dictionary.switchLanguage,exact:true}).click();const other=locale==='bn'?en:bn;await expect(dialog.getByRole('heading',{name:other.driverArrive,exact:true})).toBeVisible();await dialog.getByRole('button',{name:other.switchLanguage,exact:true}).click();await dialog.getByRole('button',{name:theme==='dark'?dictionary.switchLight:dictionary.switchDark,exact:true}).click();await dialog.getByRole('button',{name:theme==='dark'?dictionary.switchDark:dictionary.switchLight,exact:true}).click();await j.keyboard.press('Escape');await expect(dialog).not.toBeVisible();await expect(trigger).toBeFocused();await trigger.click();}const scan=await new AxeBuilder({page:j}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();expect(scan.violations).toEqual([]);await j.getByRole('dialog').getByRole('button',{name:t.confirm,exact:true}).click();await expect(j.getByRole('dialog')).not.toBeVisible();}
    await expect(n.getByText(t.completed,{exact:true})).toBeVisible();await expect(r.getByText(t.completed,{exact:true})).toBeVisible();
    const finalN=(await (await n.request.get('/api/v1/ride-requests/'+nId)).json()).data;expect(finalN.fare.kind).toBe('FINAL');expect(finalN.fare.chargePoysha).toBe(3000);expect(finalN.fare.collectionStatus).toBe('NOT_TRACKED');expect(JSON.stringify(finalN)).not.toContain('Rafiq');expect(finalN.pool).not.toHaveProperty('members');
    await n.reload();await expect(n).toHaveURL(`/${locale}/passenger/rides/${nId}`);await expect(n.getByText(t.completed,{exact:true})).toBeVisible();await j.reload();await expect(j).toHaveURL(`/${locale}/driver/pools/${pool}`);
    expect((await (await n.request.get('/api/v1/ride-requests/current')).json()).data).toBeNull();expect((await (await j.request.get('/api/v1/driver/pools/current')).json()).data).toBeNull();
  }finally{await Promise.all(contexts.map(c=>c.close().catch(()=>{})));}
});
