import {test,expect} from '@playwright/test';import type {Page} from '@playwright/test';
async function login(page:Page,name:string){await page.goto('/en/sign-in');await page.getByLabel('Email address',{exact:true}).fill(name+'@demo.dhaka.test');await page.getByLabel('Password',{exact:true}).fill(process.env.E2E_PASSWORD!);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL('/en/account');}
async function command(page:Page,path:string,body:object,method='POST'){const csrf=(await (await page.request.get('/api/v1/auth/csrf')).json()).data.csrfToken;const response=await page.request.fetch('/api/v1'+path,{method,headers:{origin:'http://127.0.0.1:3000','x-csrf-token':csrf,'idempotency-key':crypto.randomUUID()},data:body});expect(response.ok()).toBe(true);return (await response.json()).data;}
test('late real solo-fare representation cannot replace newer pooled fare when request version is unchanged',async({browser,baseURL})=>{
  test.setTimeout(60000);const contexts=await Promise.all([browser.newContext({baseURL}),browser.newContext({baseURL}),browser.newContext({baseURL})]);const [n,r,j]=await Promise.all(contexts.map(x=>x.newPage()));
  try{await login(n,'nusrat');await login(r,'rafiq');await login(j,'jashim');const quote=async(page:Page)=>command(page,'/fare-quotes',{pickupId:'banani',destinationId:'mohakhali',seats:1});const nq=await quote(n),rq=await quote(r);const nr=await command(n,'/ride-requests',{quoteId:nq.id,paymentMethod:'CASH'}),rr=await command(r,'/ride-requests',{quoteId:rq.id,paymentMethod:'CASH'});await command(j,'/driver/availability',{online:true},'PATCH');const pool=(await command(j,`/driver/requests/${nr.resourceId}/accept`,{})).resourceId;
    const old=await (await n.request.get('/api/v1/ride-requests/'+nr.resourceId)).json();expect(old.data.fare.totalPoysha).toBe(4000);await n.goto('/en/passenger/rides/'+nr.resourceId);await expect(n.getByRole('definition').filter({hasText:'40.00'}).first()).toBeVisible();await command(j,`/driver/requests/${rr.resourceId}/accept`,{});const next=await (await n.request.get('/api/v1/ride-requests/'+nr.resourceId)).json();expect(next.data.representationVersion.request).toBe(old.data.representationVersion.request);expect(next.data.representationVersion.pool).toBeGreaterThan(old.data.representationVersion.pool);await expect(n.getByRole('definition').filter({hasText:'30.00'})).toBeVisible();
    let replayed!:()=>void;const replay=new Promise<void>(resolve=>{replayed=resolve;});await n.route('**/api/v1/ride-requests/'+nr.resourceId,async route=>{await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(old)});replayed();},{times:1});await replay;await expect(n.getByRole('definition').filter({hasText:'30.00'})).toBeVisible();expect(await n.getByRole('definition').filter({hasText:'40.00'}).count()).toBe(0);
    for(const verb of ['arrive','start','complete'])await command(j,`/driver/pools/${pool}/${verb}`,{});
  }finally{await Promise.all(contexts.map(x=>x.close()));}
});

test('successful delayed prior-account mutation callback cannot navigate or reveal data after logout and new login',async({page})=>{
  const email=`boundary-${Date.now()}@test.invalid`;await page.goto('/en/sign-up');await page.getByLabel('Your name',{exact:true}).fill('Prior private actor');await page.getByLabel('Email address',{exact:true}).fill(email);for(const label of ['Password','Confirm password'])await page.getByLabel(label,{exact:true}).fill('Boundary-fixture-password-2026');await page.getByRole('button',{name:'Create an account',exact:true}).click();await expect(page).toHaveURL('/en/account');
  await page.goto('/en/passenger/book');await page.getByRole('button',{name:'Calculate fare',exact:true}).click();await expect(page.getByRole('heading',{name:'Your fare quote'})).toBeVisible();let release!:()=>void,entered!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;}),started=new Promise<void>(resolve=>{entered=resolve;});await page.route('**/api/v1/ride-requests',async route=>{const response=await route.fetch();entered();await gate;await route.fulfill({response});});await page.getByRole('button',{name:'Confirm ride request',exact:true}).click();await started;
  await page.getByRole('navigation').filter({visible:true}).getByRole('link',{name:'Your account',exact:true}).click();await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect(page).toHaveURL('/en/sign-in');await page.getByLabel('Email address',{exact:true}).fill('shirin@demo.dhaka.test');await page.getByLabel('Password',{exact:true}).fill(process.env.E2E_PASSWORD!);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL('/en/account');release();await expect(page.getByText('Shirin',{exact:true})).toBeVisible();await expect(page).toHaveURL('/en/account');expect(await page.getByRole('button',{name:'Retry original command',exact:true}).count()).toBe(0);expect(await page.getByText('Prior private actor',{exact:true}).count()).toBe(0);
});
