'use client';
import Image from 'next/image';import Link from 'next/link';import type {Statistics,RideDetail,PoolDetail} from '@dtp/contracts';
import {ProductShell} from './product-shell';import {useView} from './view-provider';import {useSession} from './session-provider';import {useOwnedQuery} from './use-owned-query';import {money,zoneLabel} from '@/i18n/format';import {errorText} from '@/i18n/catalog';import {statusLabel} from './ride-screen';
export function OverviewScreen({driver=false}:{driver?:boolean}){
  const {dictionary:t,locale}=useView();const {user}=useSession();const stats=useOwnedQuery<Statistics>(`/statistics/${driver?'driver':'passenger'}`);const current=useOwnedQuery<RideDetail|PoolDetail>(driver?'/driver/pools/current':'/ride-requests/current',true);
  const record=current.data;const occupied=record?('reservedSeats' in record?record.reservedSeats:record.pool?.reservedSeats??0):0;
  return <ProductShell role={driver?'DRIVER':'PASSENGER'}><p className="eyebrow">{t.overview}</p><h1 className="mt-2 text-3xl font-bold">{t.hello} {user?.displayName}</h1><p className="mt-2 text-muted">{driver?t.driverOverviewHelp:t.passengerOverviewHelp}</p>
    <section className="relative mt-6 overflow-hidden rounded-[18px] border border-[#35503a] bg-[#0c1814] p-6 text-[#eff6f4] md:min-h-64 md:p-8"><div className="relative z-10 max-w-[70%] md:max-w-[55%]"><p className="eyebrow !text-[#b2d3aa]">{t.storyEyebrow}</p><h2 className="mt-4 text-3xl font-bold">{t.storyTitle}<br/><span className="text-[#aff369]">{t.storyAccent}</span></h2><p className="mt-4 text-sm text-[#b8cac2]">{t.storyDescription}</p><Link className="mt-6 inline-flex min-h-12 items-center rounded-xl bg-[#aff369] px-5 font-semibold text-[#10270e]" href={`/${locale}/${driver?'driver/requests':'passenger/book'}`}>{driver?t.requests:t.bookRide}</Link></div><div className="absolute inset-y-0 right-[-15%] w-[70%] opacity-65 md:right-[-2%] md:w-[55%]"><Image src="/images/bullet-hero.webp" alt={t.bulletAlt} fill unoptimized sizes="(max-width:767px) 70vw,50vw" className="object-cover [mask-image:linear-gradient(90deg,transparent,#000_20%,#000)]"/></div></section>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1.25fr_1fr]"><section className="rounded-2xl border border-line bg-panel p-6"><h2 className="text-xl font-bold">{t.currentTrip}</h2>
      {!current.loaded?<p className="mt-4">{t.loading}</p>:current.error?<p role="alert" className="mt-4">{errorText(locale,current.error)} <button className="control px-4" onClick={current.refresh}>{t.retry}</button></p>:record?<><p className="mt-4 text-accent">{statusLabel(t,record.status)}</p>{'route' in record&&<p className="mt-3">{zoneLabel(locale,record.route.pickupId)} → {zoneLabel(locale,record.route.destinationId)}</p>}<Link className="control mt-5 px-4" href={`/${locale}/${driver?'driver/pools':'passenger/rides'}/${record.id}`}>{t.openDetails}</Link></>:<p className="mt-4 text-muted">{driver?t.noActivePool:t.noActiveRide}</p>}
      <div className="mt-6 grid grid-cols-3 gap-3" role="img" aria-label={`${t.poolOccupancy}: ${occupied}/3`}>{[0,1,2].map(i=><div className="seat-place flex items-center justify-center text-lg" key={i} data-occupied={i<occupied} aria-hidden>{i<occupied?'●':'○'}</div>)}</div><p className="mt-3 text-sm text-muted">{t.quantityHelp}</p>
    </section><section className="rounded-2xl border border-line bg-panel p-6"><h2 className="text-xl font-bold">{t.weekSummary}</h2>{!stats.loaded?<p className="mt-4">{t.loading}</p>:stats.error?<p role="alert" className="mt-4">{errorText(locale,stats.error)}</p>:stats.data&&<dl className="mt-5 grid grid-cols-2 gap-4"><dt className="text-muted">{driver?t.completedPools:t.completedRides}</dt><dd className="text-right text-2xl font-bold text-accent">{new Intl.NumberFormat(locale==='bn'?'bn-BD':'en-BD').format(stats.data.totals.trips)}</dd><dt className="text-muted">{driver?t.seatsServed:t.totalFare}</dt><dd className="text-right text-xl font-bold">{driver?new Intl.NumberFormat(locale==='bn'?'bn-BD':'en-BD').format(stats.data.totals.seats??0):money(locale,stats.data.totals.farePoysha??0)}</dd></dl>}<p className="mt-5 text-sm text-muted">{t.completedOnly}</p><Link className="control mt-5 px-4" href={`/${locale}/${driver?'driver':'passenger'}/activity`}>{t.activity}</Link></section></div>
  </ProductShell>;
}
