import test from 'node:test';
import assert from 'node:assert/strict';
import { createApplication } from '../../apps/api/dist/bootstrap.js';
import { DatabaseService } from '../../apps/api/dist/database/database.service.js';
import { seed } from '../../apps/api/dist/database/seed.js';
import { isolatedDatabase } from './isolated-db.mjs';

test('real HTTP + PostgreSQL auth: CSRF/origin, validation, roles, rotated/expired sessions, logout and safe identity',async()=>{
  const fixture=await isolatedDatabase();
  await seed(fixture.url,'Nonsecret-test-fixture-2026');
  const db=new DatabaseService(fixture.url);
  const app=await createApplication(fixture.url);
  await app.listen(0,'127.0.0.1');
  const base=await app.getUrl();
  const call=(path,method='GET',body,headers={})=>fetch(base+'/api/v1'+path,{method,headers:{'content-type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});
  try {
    assert.equal((await call('/me')).status,401);
    const bootstrap=await call('/auth/csrf');
    const oldCookie=bootstrap.headers.getSetCookie()[0].split(';')[0];
    assert.match(bootstrap.headers.getSetCookie()[0],/HttpOnly/i);
    assert.match(bootstrap.headers.getSetCookie()[0],/SameSite=Lax/i);
    const token=(await bootstrap.json()).data.csrfToken;
    const headers={cookie:oldCookie,origin:'http://127.0.0.1:3000','x-csrf-token':token};
    const input={email:'nusrat@demo.dhaka.test',password:'Nonsecret-test-fixture-2026'};
    assert.equal((await call('/auth/login','POST',input,{cookie:oldCookie})).status,403);
    assert.equal((await call('/auth/login','POST',input,{...headers,origin:'https://foreign.example'})).status,403);
    assert.equal((await call('/auth/login','POST',{...input,role:'DRIVER'},headers)).status,400);
    const login=await call('/auth/login','POST',input,headers);
    assert.equal(login.status,201);
    const cookie=login.headers.getSetCookie()[0].split(';')[0];
    assert.notEqual(cookie,oldCookie);
    const receipt=(await login.json()).data;
    assert.equal(receipt.user.role,'PASSENGER');
    assert.equal(receipt.user.displayName,'Nusrat');
    assert.deepEqual(Object.keys(receipt.user).sort(),['displayName','email','id','role']);
    assert.equal((await call('/me','GET',undefined,{cookie:oldCookie})).status,401);
    const owned=await call('/me','GET',undefined,{cookie,'x-user-id':'foreign','x-role':'DRIVER'});
    assert.match(owned.headers.get('cache-control'),/no-store/);
    assert.equal((await owned.json()).data.id,receipt.user.id);
    assert.equal((await call('/driver/vehicle','GET',undefined,{cookie,'x-role':'DRIVER'})).status,403);
    const authenticated={cookie,origin:'http://127.0.0.1:3000','x-csrf-token':receipt.csrfToken};
    assert.equal((await call('/auth/logout','POST',{},authenticated)).status,201);
    assert.equal((await call('/me','GET',undefined,{cookie})).status,401);
    const fresh=await call('/auth/csrf');
    const anon=fresh.headers.getSetCookie()[0].split(';')[0];
    const freshHeaders={cookie:anon,origin:'http://127.0.0.1:3000','x-csrf-token':(await fresh.json()).data.csrfToken};
    const signup={name:'বাংলা ব্যবহারকারী',email:`new-${Date.now()}@test.invalid`,password:'Unicode-অপরিবর্তিত-Password'};
    assert.equal((await call('/auth/register','POST',{...signup,role:'DRIVER'},freshHeaders)).status,400);
    const registered=await call('/auth/register','POST',signup,freshHeaders);
    assert.equal(registered.status,201);
    const account=(await registered.json()).data;
    const newCookie=registered.headers.getSetCookie()[0].split(';')[0];
    assert.equal(account.user.role,'PASSENGER');
    assert.equal(account.user.displayName,signup.name);
    assert.match((await db.query('SELECT password_hash FROM users WHERE id=$1',[account.user.id])).rows[0].password_hash,/^\$argon2id\$/);
    await db.query("UPDATE sessions SET expires_at=clock_timestamp()-interval '1 second',created_at=clock_timestamp()-interval '2 seconds' WHERE user_id=$1",[account.user.id]);
    assert.equal((await call('/me','GET',undefined,{cookie:newCookie})).status,401);
    const driverBoot=await call('/auth/csrf');
    const driverHeaders={cookie:driverBoot.headers.getSetCookie()[0].split(';')[0],origin:'http://127.0.0.1:3000','x-csrf-token':(await driverBoot.json()).data.csrfToken};
    const driverLogin=await call('/auth/login','POST',{email:'jashim@demo.dhaka.test',password:input.password},driverHeaders);
    const driverCookie=driverLogin.headers.getSetCookie()[0].split(';')[0];
    const vehicle=(await (await call('/driver/vehicle','GET',undefined,{cookie:driverCookie})).json()).data;
    assert.equal(vehicle.displayName,'Bullet'); assert.equal(vehicle.capacity,3);
    assert.equal((await call('/me','GET',undefined,{cookie:'dtp-session=forged'})).status,401);
    const errorBoot=await call('/auth/csrf');
    const errorHeaders={cookie:errorBoot.headers.getSetCookie()[0].split(';')[0],origin:'http://127.0.0.1:3000','x-csrf-token':(await errorBoot.json()).data.csrfToken};
    const failed=await call('/auth/login','POST',{email:'missing@test.invalid',password:'wrong'},errorHeaders);
    assert.equal(failed.status,401); assert.equal((await failed.json()).error.code,'INVALID_CREDENTIALS');
    for(let i=0;i<14;i++) await call('/auth/login','POST',{email:'limited@test.invalid',password:'wrong'},errorHeaders);
    assert.equal((await call('/auth/login','POST',{email:'limited@test.invalid',password:'wrong'},errorHeaders)).status,401);
    assert.equal((await call('/auth/login','POST',{email:'limited@test.invalid',password:'wrong'},errorHeaders)).status,429);
  } finally {await app.close(); await db.onModuleDestroy(); await fixture.close();}
});
