import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {createRequire} from 'node:module';
const pg=createRequire(new URL('../../apps/api/package.json',import.meta.url))('pg');
import {isolatedDatabase} from './isolated-db.mjs';import {httpApp,book} from './http-fixture.mjs';import {seed} from '../../apps/api/dist/database/seed.js';import {DatabaseService} from '../../apps/api/dist/database/database.service.js';
async function setup(){const fixture=await isolatedDatabase();await seed(fixture.url,'Nonsecret-test-fixture-2026');const db=new pg.Pool({connectionString:fixture.url}),http=await httpApp(fixture.url),j=await http.login('jashim'),n=await http.login('nusrat'),r=await http.login('rafiq');await j.call('/driver/availability','PATCH',{online:true},randomUUID());return {fixture,db,http,j,n,r,async close(){await http.close();await db.end();await fixture.close();}};}
async function accept(j,id){const x=await j.call(`/driver/requests/${id}/accept`,'POST',{},randomUUID());assert.equal(x.status,201);return x.data.resourceId;}
async function action(j,id,verb){return j.call(`/driver/pools/${id}/${verb}`,'POST',{},randomUUID());}
async function contended(db,fragment){const deadline=Date.now()+1500;while(Date.now()<deadline){if((await db.query("SELECT 1 FROM pg_stat_activity WHERE datname=current_database() AND wait_event_type='Lock' AND query LIKE $1",['%'+fragment+'%'])).rowCount)return;await new Promise(resolve=>setTimeout(resolve,10));}assert.fail('Second real connection did not wait on parent lock');}
function holdFirstParent(http){const service=http.app.get(DatabaseService),original=service.transaction.bind(service);let release,entered;const acquired=new Promise(resolve=>{entered=resolve;}),gate=new Promise(resolve=>{release=resolve;});let once=true;service.transaction=(operation,readOnly)=>original(async client=>{const query=client.query.bind(client);client.query=async(...args)=>{const result=await query(...args);if(once&&String(args[0]).includes('driver_profiles')&&String(args[0]).includes('FOR UPDATE')){once=false;entered();await gate;}return result;};try{return await operation(client);}finally{client.query=query;}},readOnly);return {acquired,release:()=>release(),restore:()=>{service.transaction=original;}};}

for(const first of ['offline','accept'])test(`availability race: ${first} obtains driver lock first`,{timeout:12000},async()=>{
  const f=await setup();let gate;
  try{const id=await book(f.n);gate=holdFirstParent(f.http);const offline=()=>f.j.call('/driver/availability','PATCH',{online:false},randomUUID()),acceptance=()=>f.j.call(`/driver/requests/${id}/accept`,'POST',{},randomUUID());const one=first==='offline'?offline():acceptance();await gate.acquired;const two=first==='offline'?acceptance():offline();await contended(f.db,'driver_profiles');gate.release();const a=await one,b=await two;gate.restore();assert.equal(a.status,first==='offline'?200:201);assert.equal(b.status,409);assert.equal(b.error.code,first==='offline'?'DRIVER_OFFLINE':'ACTIVE_POOL_EXISTS');assert.equal((await f.n.call('/ride-requests/'+id)).data.status,first==='offline'?'REQUESTED':'MATCHED');assert.equal((await f.db.query('SELECT online FROM driver_profiles WHERE user_id=$1',[f.j.user.id])).rows[0].online,first!=='offline');assert.equal((await f.db.query('SELECT count(*)::int n FROM pool_memberships')).rows[0].n,first==='offline'?0:1);
  }finally{gate?.release();gate?.restore();await f.close();}
});

test('arrival first blocks actually contending passenger cancellation without fare/event damage',{timeout:12000},async()=>{
  const f=await setup();let gate;
  try{const id=await book(f.n),pool=await accept(f.j,id);gate=holdFirstParent(f.http);const arrival=action(f.j,pool,'arrive');await gate.acquired;const cancel=f.n.call(`/ride-requests/${id}/cancel`,'POST',{reason:'Late race'},randomUUID());await contended(f.db,'driver_profiles');gate.release();assert.equal((await arrival).status,201);assert.equal((await cancel).error.code,'CANCELLATION_CLOSED');gate.restore();const detail=(await f.n.call('/ride-requests/'+id)).data;assert.equal(detail.status,'DRIVER_ARRIVED');assert.equal(detail.fare.totalPoysha,4000);assert.equal((await f.db.query("SELECT count(*)::int n FROM ride_events WHERE event_type='PASSENGER_CANCEL'")).rows[0].n,0);
  }finally{gate?.release();gate?.restore();await f.close();}
});

test('completed remaining pool leaves earlier canceled member and event byte-for-byte intact',{timeout:12000},async()=>{
  const f=await setup();try{const id=await book(f.n),other=await book(f.r),pool=await accept(f.j,id);await accept(f.j,other);assert.equal((await f.n.call(`/ride-requests/${id}/cancel`,'POST',{reason:'Earlier'},randomUUID())).status,201);const before=(await f.db.query('SELECT row_to_json(r) value FROM ride_requests r WHERE id=$1',[id])).rows[0].value,events=(await f.db.query('SELECT * FROM ride_events WHERE ride_request_id=$1 ORDER BY id',[id])).rows;for(const verb of ['arrive','start','complete'])assert.equal((await action(f.j,pool,verb)).status,201);assert.deepEqual((await f.db.query('SELECT row_to_json(r) value FROM ride_requests r WHERE id=$1',[id])).rows[0].value,before);assert.deepEqual((await f.db.query('SELECT * FROM ride_events WHERE ride_request_id=$1 ORDER BY id',[id])).rows,events);assert.equal((await f.r.call('/ride-requests/'+other)).data.fare.chargePoysha,4000);const response=await f.j.call('/statistics/driver');assert.equal(response.status,200);assert.equal(response.data.totals.seats,1);
  }finally{await f.close();}
});

test('expired quote and session cannot leak receipt; same verified owner replays completed create once',{timeout:12000},async()=>{
  const f=await setup();try{const rule=(await f.db.query("SELECT * FROM route_rules WHERE destination_id='mohakhali'")).rows[0];const quote=(await f.db.query(`INSERT INTO fare_quotes(owner_id,route_id,pickup_id,destination_id,group_id,group_version,seats,demo_distance_m,base_poysha,rate_poysha,discount_poysha,policy_version,expires_at) VALUES($1,$2,'banani','mohakhali','BANANI_V1',1,1,2000,2000,1000,1000,'fare-v1',clock_timestamp()+interval '1 second') RETURNING id`,[f.n.user.id,rule.id])).rows[0];const key=randomUUID(),body={quoteId:quote.id,paymentMethod:'CASH'},created=await f.n.call('/ride-requests','POST',body,key);assert.equal(created.status,201);const pool=await accept(f.j,created.data.resourceId);for(const verb of ['arrive','start','complete'])assert.equal((await action(f.j,pool,verb)).status,201);while(!(await f.db.query('SELECT expires_at<=clock_timestamp() expired FROM fare_quotes WHERE id=$1',[quote.id])).rows[0].expired)await new Promise(resolve=>setTimeout(resolve,20));const before=(await f.db.query('SELECT count(*)::int n FROM ride_events')).rows[0].n;await f.db.query("UPDATE sessions SET expires_at=clock_timestamp()-interval '1 second',created_at=clock_timestamp()-interval '2 seconds' WHERE user_id=$1",[f.n.user.id]);const expired=await f.n.call('/ride-requests','POST',body,key);assert.equal(expired.status,401);assert.equal(expired.data,undefined);const foreign=await f.r.call('/ride-requests','POST',body,key);assert.equal(foreign.status,404);assert.equal(foreign.data,undefined);const n=await f.http.login('nusrat');assert.deepEqual((await n.call('/ride-requests','POST',body,key)).data,created.data);assert.equal((await n.call('/ride-requests','POST',body,randomUUID())).error.code,'QUOTE_EXPIRED');assert.equal((await f.db.query('SELECT count(*)::int n FROM ride_events')).rows[0].n,before);assert.equal((await f.db.query('SELECT count(*)::int n FROM ride_requests WHERE quote_id=$1',[quote.id])).rows[0].n,1);
  }finally{await f.close();}
});

test('HTTPS-origin configuration issues Secure cookies and rejects untrusted forwarding origin',{timeout:10000},async()=>{
  const f=await setup();const original=process.env.APP_ORIGIN;
  try{process.env.APP_ORIGIN='https://pool.example.test';const response=await fetch(f.http.base+'/api/v1/auth/csrf');assert.match(response.headers.getSetCookie()[0],/; Secure/i);const token=(await response.json()).data.csrfToken,headers={cookie:response.headers.getSetCookie()[0].split(';')[0],'content-type':'application/json','x-csrf-token':token,origin:'http://127.0.0.1:3000','x-forwarded-proto':'https','x-forwarded-host':'pool.example.test'};const rejected=await fetch(f.http.base+'/api/v1/auth/login',{method:'POST',headers,body:JSON.stringify({email:'nusrat@demo.dhaka.test',password:'Nonsecret-test-fixture-2026'})});assert.equal(rejected.status,403);headers.origin='https://pool.example.test';const valid=await fetch(f.http.base+'/api/v1/auth/login',{method:'POST',headers,body:JSON.stringify({email:'nusrat@demo.dhaka.test',password:'Nonsecret-test-fixture-2026'})});assert.equal(valid.status,201);assert.match(valid.headers.getSetCookie()[0],/; Secure/i);
  }finally{if(original===undefined)delete process.env.APP_ORIGIN;else process.env.APP_ORIGIN=original;await f.close();}
});
