'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';import type {Statistics,Locale} from '@/lib/contracts';
import {ProductShell} from './product-shell';import {useView} from './view-provider';import {useOwnedQuery} from './use-owned-query';import {useRideUI} from './ride-ui-provider';import {errorText,messages} from '@/i18n/catalog';import {money} from '@/i18n/format';
function day(locale:Locale,value:string){return new Intl.DateTimeFormat(locale==='bn'?'bn-BD':'en-BD',{day:'numeric',month:'short',timeZone:'Asia/Dhaka'}).format(new Date(value+'T00:00:00+06:00'));}
function CountChart({stats,metric,label,locale}:{stats:Statistics;metric:'trips'|'farePoysha'|'seats';label:string;locale:Locale}){
  const frame=useRef<HTMLDivElement>(null);const [chartWidth,setChartWidth]=useState(680);
  useEffect(()=>{if(!frame.current)return;const observer=new ResizeObserver(entries=>{const measured=entries[0]?.contentRect.width;if(measured)setChartWidth(Math.max(260,Math.round(measured)));});observer.observe(frame.current);return()=>observer.disconnect();},[]);
  const largest=Math.max(1,...stats.daily.map(row=>row[metric]??0));const width=(chartWidth-80)/stats.daily.length;const ticks=[0,largest/2,largest];
  return <figure className="rounded-2xl border border-line bg-panel p-5"><figcaption className="text-xl font-bold">{label}</figcaption>
    <div ref={frame} className="mt-5"><svg role="img" aria-label={label} viewBox={`0 0 ${chartWidth} 245`} className="block h-[245px] w-full"><title>{label}</title><desc>{day(locale,stats.from)} — {day(locale,stats.to)} · {messages(locale).dhakaTime}</desc>
      {ticks.map((n,i)=><g key={i}><line x1="60" x2={chartWidth-20} y1={200-i*85} y2={200-i*85} stroke="var(--line)"/><text x="52" y={204-i*85} textAnchor="end" fill="var(--muted)" fontSize="12">{new Intl.NumberFormat(locale==='bn'?'bn-BD':'en-BD',{maximumFractionDigits:1}).format(metric==='farePoysha'?n/100:n)}</text></g>)}
      {stats.daily.map((row,i)=>{const value=row[metric]??0,height=value/largest*170;return <rect key={row.date} x={60+i*width+width*.2} y={200-height} width={Math.max(1,width*.6)} height={height} rx="3" fill="var(--accent)"><title>{day(locale,row.date)}: {metric==='farePoysha'?money(locale,value):new Intl.NumberFormat(locale==='bn'?'bn-BD':'en-BD').format(value)}</title></rect>;})}
      {[0,Math.floor((stats.daily.length-1)/2),stats.daily.length-1].filter((n,i,a)=>a.indexOf(n)===i).map(i=><text key={i} x={60+(i+.5)*width} y="225" textAnchor="middle" fill="var(--muted)" fontSize="12">{day(locale,stats.daily[i]!.date)}</text>)}
    </svg></div>
  </figure>;
}
export function StatisticsScreen({driver=false}:{driver?:boolean}){
  const {dictionary:t,locale}=useView();const params=useSearchParams();const router=useRouter();const ui=useRideUI();const query=useOwnedQuery<Statistics>(`/statistics/${driver?'driver':'passenger'}?${params.toString()}`);const s=query.data;
  const draft=ui.statsDraft??{from:params.get('from')??s?.from??'',to:params.get('to')??s?.to??''};const count=(n:number)=>new Intl.NumberFormat(locale==='bn'?'bn-BD':'en-BD').format(n);
  return <ProductShell role={driver?'DRIVER':'PASSENGER'}><h1 className="text-3xl font-bold">{t.activity}</h1><p className="mt-2 text-muted">{t.completedOnly}</p>
    <form noValidate onSubmit={e=>{e.preventDefault();router.replace(`/${locale}/${driver?'driver':'passenger'}/activity?`+new URLSearchParams(draft));}} className="mt-6 flex flex-wrap items-end gap-4 rounded-2xl border border-line bg-panel p-5"><div className="min-w-0 grow"><label className="field-label" htmlFor="date-from">{t.fromDate}</label><input id="date-from" type="date" value={draft.from} onChange={e=>ui.setStatsDraft({...draft,from:e.target.value})}/></div><div className="min-w-0 grow"><label className="field-label" htmlFor="date-to">{t.toDate}</label><input id="date-to" type="date" value={draft.to} onChange={e=>ui.setStatsDraft({...draft,to:e.target.value})}/></div><button className="primary-action">{t.applyFilters}</button></form>
    <p className="mt-3 text-sm text-muted">{t.periodHelp}</p>
    {!query.loaded?<p className="mt-6">{t.loading}</p>:query.error?<p role="alert" className="mt-6">{errorText(locale,query.error)} <button className="control px-4" onClick={query.refresh}>{t.retry}</button></p>:s&&<>
      <div className="mt-6 grid gap-4 sm:grid-cols-3"><section className="rounded-2xl border border-line bg-panel p-5"><h2 className="text-muted">{driver?t.completedPools:t.completedRides}</h2><p className="mt-2 text-3xl font-bold text-accent">{count(s.totals.trips)}</p></section><section className="rounded-2xl border border-line bg-panel p-5"><h2 className="text-muted">{driver?t.seatsServed:t.totalFare}</h2><p className="mt-2 text-3xl font-bold text-accent">{driver?count(s.totals.seats??0):money(locale,s.totals.farePoysha??0)}</p></section><section className="rounded-2xl border border-line bg-panel p-5"><h2 className="text-muted">{driver?t.seatUtilization:t.poolingDiscount}</h2><p className="mt-2 text-3xl font-bold text-accent">{driver?new Intl.NumberFormat(locale==='bn'?'bn-BD':'en-BD',{style:'percent',maximumFractionDigits:1}).format(s.totals.utilization??0):money(locale,s.totals.discountPoysha??0)}</p></section></div>
      {!s.totals.trips&&<p className="mt-6">{t.noCompletedData}</p>}
      <p className="mt-6 text-sm text-muted">{t.graphPeriod}: {day(locale,s.from)} — {day(locale,s.to)} · {t.dhakaTime}</p>
      <div className="mt-4 grid gap-4 xl:grid-cols-2"><CountChart stats={s} locale={locale} metric="trips" label={driver?t.dailyPools:t.dailyRides}/><CountChart stats={s} locale={locale} metric={driver?'seats':'farePoysha'} label={driver?t.dailySeats:t.dailyFare}/></div>
      <section tabIndex={0} className="mt-6 overflow-x-auto rounded-2xl border border-line bg-panel p-5" aria-label={t.exactData}><table className="w-full text-left text-sm"><caption className="mb-4 text-left text-lg font-bold">{t.exactData}</caption><thead><tr><th scope="col" className="p-2">{t.date}</th><th scope="col" className="p-2">{driver?t.completedPools:t.completedRides}</th><th scope="col" className="p-2">{driver?t.seatsServed:t.totalFare}</th><th scope="col" className="p-2">{driver?t.capacityDenominator:t.poolingDiscount}</th></tr></thead><tbody>{s.daily.map(row=><tr key={row.date} className="border-t border-line"><th scope="row" className="p-2 font-normal">{day(locale,row.date)}</th><td className="p-2">{count(row.trips)}</td><td className="p-2">{driver?count(row.seats??0):money(locale,row.farePoysha??0)}</td><td className="p-2">{driver?count(row.capacity??0):money(locale,row.discountPoysha??0)}</td></tr>)}</tbody></table></section>
      {driver&&<p className="mt-3 text-sm text-muted">{t.utilizationHelp}</p>}
    </>}
  </ProductShell>;
}
